# Generated by Django 4.0.6 on 2022-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
