# Generated by Django 4.0.6 on 2022-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
