# Generated by Django 4.0.6 on 2022-07-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birth_date',
        ),
    ]
