# Generated by Django 4.0.6 on 2022-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='250', upload_to='images/user', width_field='250'),
        ),
    ]
