# Generated by Django 4.0.6 on 2022-07-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0009_alter_users_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
    ]
